"""
OKF emitter (Phase 3) — the curated-knowledge layer (locked decision #8).

OKF (Open Knowledge Format, Google Cloud, Apache-2.0) is deliberately boring:
a directory of Markdown files with YAML frontmatter (type / title /
description / resource / tags), relationships as plain markdown links. No
runtime, no SDK. That's the point — humans read it on GitHub, agents read it
as files.

Three roles here (strategy §8):
  1. Portable team artifact — a `.knowledge/` bundle per repo the team can
     commit; new teammates (and their agents) skip re-analysis.
  2. Agent-consumable context — any MCP agent reads the bundle directly.
  3. The "why" layer — each doc is ALSO embedded into the vector store under
     space='okf', so questions like "why is it structured this way?" retrieve
     curated intent, not just code.

Content comes from the existing analysis layer (services/analysis/) plus
graph statistics. OKF is OUTPUT-ONLY, never load-bearing (risk register):
graph + vectors stay the source of truth; worst case we regenerate markdown.
"""

import logging
import os
from typing import Any, Dict, List

from app.core.config import settings
from app.core.logging import log_event, stage_timer

logger = logging.getLogger(__name__)

OKF_VERSION = "0.1"


def _frontmatter(doc_type: str, title: str, description: str,
                 tags: List[str], resource: str) -> str:
    tag_lines = "\n".join(f"  - {t}" for t in tags)
    return (
        "---\n"
        f"okf: \"{OKF_VERSION}\"\n"
        f"type: {doc_type}\n"
        f"title: \"{title}\"\n"
        f"description: \"{description}\"\n"
        f"resource: \"{resource}\"\n"
        f"tags:\n{tag_lines}\n"
        "---\n\n"
    )


def _render(value: Any) -> str:
    """Analysis outputs are strings / lists / dicts — render all as markdown."""
    if isinstance(value, str):
        return value + "\n"
    if isinstance(value, list):
        return "\n".join(f"- {item}" for item in value) + "\n"
    if isinstance(value, dict):
        return "\n".join(f"- **{k}**: {v}" for k, v in value.items()) + "\n"
    return str(value) + "\n"


def emit_okf_bundle(repo_id: str, repo_path: str) -> Dict[str, Any]:
    """
    Generate `.knowledge/` under DATA_DIR/okf/<repo_id>/ and embed each doc
    into the vector store (space='okf'). Returns a manifest. Never raises —
    the knowledge layer is additive; its failure must not fail ingestion.
    """
    try:
        with stage_timer(logger, "okf.emit", repo_id=repo_id) as ctx:
            from app.services.analysis.aggregator import run_full_analysis
            analysis = run_full_analysis(repo_path)

            try:
                from app.services.graph_store import graph_store
                graph_stats = graph_store.stats(repo_id)
            except Exception:
                graph_stats = {}

            bundle_dir = os.path.join(settings.DATA_DIR, "okf", repo_id, ".knowledge")
            os.makedirs(bundle_dir, exist_ok=True)

            sections = {
                "project-summary": ("overview", "Project summary",
                                    analysis.get("project_summary", "")),
                "architecture": ("architecture", "Architecture",
                                 analysis.get("architecture", "")),
                "entry-points": ("guide", "Entry points",
                                 analysis.get("entry_points", [])),
                "folder-responsibilities": ("architecture", "Folder responsibilities",
                                            analysis.get("folder_responsibilities", {})),
                "reading-order": ("guide", "Suggested reading order",
                                  analysis.get("reading_order", [])),
                "safe-contributions": ("guide", "Safe first contributions",
                                       analysis.get("safe_contributions", [])),
                "feature-flow": ("guide", "Feature flow",
                                 analysis.get("feature_flow", "")),
            }

            docs: List[Dict[str, str]] = []
            for slug, (doc_type, title, content) in sections.items():
                body = _frontmatter(doc_type, title,
                                    f"{title} for repository {repo_id} "
                                    "(generated by the AI Engineering Copilot analysis layer)",
                                    ["codebase", repo_id, doc_type],
                                    f"repo://{repo_id}")
                body += f"# {title}\n\n{_render(content)}"
                if slug == "architecture" and graph_stats:
                    body += (
                        "\n## Knowledge-graph shape\n\n"
                        f"- Nodes: {graph_stats.get('nodes', 0)}\n"
                        + "".join(f"- {k} edges: {v}\n"
                                  for k, v in sorted(
                                      graph_stats.get("edges_by_kind", {}).items()))
                        + f"- Low-confidence edges (marked for review): "
                          f"{graph_stats.get('low_confidence_edges', 0)}\n"
                    )
                rel_path = f".knowledge/{slug}.md"
                with open(os.path.join(bundle_dir, f"{slug}.md"), "w",
                          encoding="utf-8") as f:
                    f.write(body)
                docs.append({"file_path": rel_path, "content": body})

            # Index: entry point of the bundle, links every doc (OKF pattern).
            index_body = _frontmatter("index", f"Knowledge bundle: {repo_id}",
                                      "Curated knowledge for agents and humans",
                                      ["okf", repo_id], f"repo://{repo_id}")
            index_body += "# Knowledge bundle\n\n" + "\n".join(
                f"- [{slug}]({slug}.md)" for slug in sections)
            with open(os.path.join(bundle_dir, "README.md"), "w", encoding="utf-8") as f:
                f.write(index_body)

            embedded = _embed_docs(repo_id, docs)
            ctx.update(docs=len(docs), embedded=embedded)
            return {"status": "success", "bundle_dir": bundle_dir,
                    "docs": len(docs), "embedded": embedded}
    except Exception as e:
        log_event(logger, "okf.emit_failed", level=logging.ERROR,
                  repo_id=repo_id, error=str(e))
        return {"status": "failed", "error": str(e)}


def _embed_docs(repo_id: str, docs: List[Dict[str, str]]) -> int:
    """Embed OKF docs as chunks under space='okf' (the third retrieval source).
    Re-emission replaces the previous bundle's chunks (paths are stable)."""
    try:
        from app.services.embeddings import current_model_id, generate_embeddings
        from app.services.vector_store import vector_metadata_store

        vector_metadata_store.remove_files(repo_id, [d["file_path"] for d in docs])
        chunks = [{
            "file_path": d["file_path"],
            "chunk_index": 0,
            "content": d["content"],
            "start_line": 1,
            "end_line": d["content"].count("\n") + 1,
        } for d in docs]
        embeddings = generate_embeddings([c["content"] for c in chunks])
        vector_metadata_store.store_chunks(
            repo_id, chunks, embeddings, updated_hashes={},
            model_id=current_model_id(), space="okf")
        return len(chunks)
    except Exception as e:
        log_event(logger, "okf.embed_failed", level=logging.WARNING,
                  repo_id=repo_id, error=str(e))
        return 0
